---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.14
  commands:
  - make
- name: lint
  image: golang:1.14
  commands:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
  - go mod download
  - make lint
- name: vet
  image: golang:1.14
  commands:
  - go vet ./...
- name: test
  image: golang:1.14
  commands:
  - make test